function playerBalance = openingScreen()
% Creates a figure for the Blackjack game where the user selects a starting balance

set(0, 'DefaultFigureWindowStyle', 'docked');
warning('off', 'images:imshow:magnificationMustBeFitForDockedFigure');

% Create a figure window
fig = figure('Name', 'Blackjack', 'NumberTitle', 'off', ...
    'MenuBar', 'none', 'ToolBar', 'none');


% Add a title at the top
titleText = uicontrol('Style', 'text', ...
    'String', 'BLACKJACK', ...
    'FontSize', 50, ...
    'FontWeight', 'bold', ...
    'ForegroundColor', 'red', ...
    'BackgroundColor', get(fig, 'Color'), ...
    'Position', [475, 350, 450, 80]); % Center horizontally

% Add the "You Won!" message at the top
money = uicontrol('Style', 'text', ...
    'String', 'Choose how much money you have You are always going all in!', ...
    'FontSize', 15, ... % Larger font size for a bigger window
    'FontWeight', 'bold', ...
    'ForegroundColor', 'black', ...
    'BackgroundColor', get(fig, 'Color'), ...
    'Position', [500, 275, 375, 50]); % [x, y, width, height]

% Add buttons for the three options
button100 = uicontrol('Style', 'pushbutton', ...
    'String', '$100', ...
    'FontSize', 15, ...
    'Position', [650, 200, 100, 50], ... % Center button
    'Callback', @(src, event) setBalance(100));

button1000 = uicontrol('Style', 'pushbutton', ...
    'String', '$1000', ...
    'FontSize', 15, ...
    'Position', [650, 150, 100, 50], ... % Center button
    'Callback', @(src, event) setBalance(1000));

button100000 = uicontrol('Style', 'pushbutton', ...
    'String', '$100000', ...
    'FontSize', 15, ...
    'Position', [650, 100, 100, 50], ... % Center button
    'Callback', @(src, event) setBalance(100000));

% Variable to store the selected balance
selectedBalance = [];

    function setBalance(amount)
        % Callback to set the balance and close the figure
        selectedBalance = amount;
        uiresume(fig); % Resume execution after button click
    end

% Pause execution until a button is clicked
uiwait(fig);

% Assign the selected balance to the output
playerBalance = selectedBalance;

% Close the figure
close(fig);


end
