function tie()
% Creates a screen to display a tie message

% Create a figure window
fig = figure('Name', 'Blackjack - Tie Screen', ...
    'NumberTitle', 'off', ...
    'MenuBar', 'none', ...
    'ToolBar', 'none');

% Add the "It's a Tie!" message at the top
tieText = uicontrol('Style', 'text', ...
    'String', 'It''s a Tie!', ...
    'FontSize', 50, ...
    'FontWeight', 'bold', ...
    'ForegroundColor', 'cyan', ...
    'BackgroundColor', get(fig, 'Color'), ...
    'Position', [475, 350, 450, 80]); % [x, y, width, height]

% Add the "Play again..." message at the bottom
playAgainText = uicontrol('Style', 'text', ...
    'String', 'Play Again!', ...
    'FontSize', 15, ...
    'FontWeight', 'normal', ...
    'ForegroundColor', 'black', ...
    'BackgroundColor', get(fig, 'Color'), ...
    'Position', [500, 275, 400, 50]); % [x, y, width, height]

% Add a "Continue" button to close the window
continueButton = uicontrol('Style', 'pushbutton', ...
    'String', 'Continue', ...
    'FontSize', 10, ...
    'Position', [650, 200, 100, 50], ...
    'Callback', @(src, event) uiresume(fig)); % Resume execution when clicked

% Pause to display the screen
uiwait(fig);

% Close the figure after the button is clicked
close(fig);
end
