function win()
% Creates a larger screen to display a winning message

% Create a larger figure window
fig = figure('Name', 'Blackjack - Win Screen', ...
    'NumberTitle', 'off', ...
    'MenuBar', 'none', ...
    'ToolBar', 'none');

% Add the "You Won!" message at the top
winText = uicontrol('Style', 'text', ...
    'String', 'You Won!', ...
    'FontSize', 50, ... % Larger font size for a bigger window
    'FontWeight', 'bold', ...
    'ForegroundColor', 'green', ...
    'BackgroundColor', get(fig, 'Color'), ...
    'Position', [475, 350, 450, 80]); % [x, y, width, height]

% Add the "Keep playing..." message at the bottom
keepPlayingText = uicontrol('Style', 'text', ...
    'String', 'Keep playing until you lose all your money', ...
    'FontSize', 15, ... % Adjusted font size
    'FontWeight', 'normal', ...
    'ForegroundColor', 'black', ...
    'BackgroundColor', get(fig, 'Color'), ...
    'Position', [500, 275, 400, 50]); % [x, y, width, height]

% Add a "Continue" button to close the window
continueButton = uicontrol('Style', 'pushbutton', ...
    'String', 'Continue', ...
    'FontSize', 10, ... % Slightly larger button text
    'Position', [650, 200, 100, 50], ... % Centered button
    'Callback', @(src, event) uiresume(fig)); % Resume execution when clicked

% Pause to display the screen
uiwait(fig);

% Close the figure after the button is clicked
close(fig);
end
